# Generated by Django 4.2.30 on 2026-08-27 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sessions_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], db_index=True, default='CONFIRMED', max_length=10)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, help_text='Client-provided key for safe retries.', max_length=255, null=True)),
                ('request_id', models.CharField(blank=True, default='', help_text='Correlation ID for debugging.', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='sessions_app.session')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bookings',
            },
        ),
        migrations.CreateModel(
            name='IdempotencyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('response_status', models.IntegerField()),
                ('response_body', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookings.booking')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sessions_app.session')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idempotency_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'idempotency_records',
            },
        ),
        migrations.CreateModel(
            name='BookingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('BOOKING_CONFIRMED', 'Booking Confirmed'), ('BOOKING_REJECTED_CAPACITY', 'Rejected: Capacity Full'), ('BOOKING_REJECTED_DUPLICATE', 'Rejected: Duplicate'), ('BOOKING_REJECTED_STARTED', 'Rejected: Session Started'), ('BOOKING_CANCELLED', 'Booking Cancelled')], db_index=True, max_length=30)),
                ('request_id', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='bookings.booking')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_events', to='sessions_app.session')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'booking_events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='idempotencyrecord',
            constraint=models.UniqueConstraint(fields=('key', 'user'), name='unique_idempotency_key_per_user'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['user', 'session'], name='idx_booking_user_session'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'CONFIRMED')), fields=('user', 'session'), name='unique_confirmed_booking_per_user_session'),
        ),
    ]
